apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:ANG08gqlKOA=,iv:C+AmqKPhLx5OcH4GaUG/JslT9y8pTYYWXPWK2aw6dmI=,tag:eC5YedjMh6d3UDHTC5TSlQ==,type:str]
    password: ENC[AES256_GCM,data:7G4J6mRUCDdFkZDD,iv:BM8wuqA3lZ9jd9cUCmhT+StMWR1k55qn6ZFyQqazGY8=,tag:ZToP0xz2a6En0TQCzLqnuQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/sandbox-latam-xp/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2019-12-30T18:40:58Z'
        enc: CiQAILtUdnJffOcKPW2pi7wqaIYtgAWjci1ueEUvxvkFg2i5U6kSSQAcaZWkYCjYYjqzA6vaSn+qnrx1iKVE0IVasnsjPexMH6EX3sQW6Q2bR7tDly6swpbIF0s//tGXXQIZGquWUOOk9+vq6S7keJ0=
    azure_kv: []
    lastmodified: '2019-12-30T18:41:00Z'
    mac: ENC[AES256_GCM,data:W7JZZTQK4FIJlhnjligki0uRC79QVsRNSEr8NP1GoqZSCeZFfGAfTx9lY3shfHw1eBzPfZTNxYBh6/MPZ9Us4hTzk3m4KEzu3sxVItOoVa6PRrdVCreUQMMGbj/rUcvlywdPVeMio6CrxAgDiarwvxJ2ET+dZTDHTg+Z+wh6dRU=,iv:0WK/k0rmt1pp8CadHiQr3HqcyTe/R3TuF2sWX7S+wa4=,tag:Ng8qpCIG+fWxpONNH9eBYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
